// <auto-generated />
namespace Online_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OnlineStoreInitail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OnlineStoreInitail));
        
        string IMigrationMetadata.Id
        {
            get { return "201710191024492_Online Store Initail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
